### PR TITLE
Basic search, uses fake/test data

### PR DESCRIPTION
**Pull request by gregsbarr**

### CODE REVIEW

**Comment by WERUreo** [comment]
Are you by chance using Xcode 7.3 beta?  The reason I ask is because I'm getting errors everywhere you're using ```#selector```, which is a change that is coming with Swift 2.2.

**Comment by WERUreo** [comment]
Also, I'm getting a nasty Segmentation Fault when I try to build.  I actually went through and changed all the ```#selector``` calls to use ```Selector()``` so that it would build in Swift 2.1 for me, and now I get a segfault when trying to build the FindPetsQuery.swift.

**Comment by gregsbarr** [comment]
So sorry, yeah I'm using 7.3. I shouldn't have assumed everyone was using the latest. Thanks for making the changes for #selector. You still having trouble with FindPetsQuery.swift?

Greg

----- Reply message -----

**Comment by WERUreo** [comment]
No worries.  Honestly, Swift 2.2 is so close to being released, there may not be much of a reason to switch back to Selector() only to have to change it back.  I'm more troubled by this other build problem I'm having.

**Comment by gregsbarr** [comment]
Is build still failing for you? I looked thru FindPetsQuery, nothing really jumps out, but couple things to check: I'm using local functions, also using "raw" type for Optional in let candidateValue: Optional. Also, you might try commenting out code to narrow down the culprit. That's served me well in the past tracking down hard-to-find bugs.

Greg


----- Reply message -----

**Comment by ToxicBakery** [comment]
Why not use travis to run builds? I find that makes it a bit easier to stay consistent and it helps keep people away from bleeding edge as travis is always a little behind on updating their images/resources from what I have seen.

**Comment by WERUreo** [comment]
I actually just set Travis up on this repo last night.  I really do like it.

**Comment by WERUreo** [comment]
By the way, I didn't really have a just to look at it yesterday, Greg.  I'm gonna try to work through it today and figure it out.

**Pull request merged**
